import clsx from 'clsx';
import type { Metadata } from 'next';
import { Charm } from 'next/font/google';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const charm = Charm({
  subsets: ['latin'],
  weight: ['400'],
  style: ['normal'],
  variable: '--font-charm',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={clsx(charm.variable, 'antialiased')}>{children}</body>
    </html>
  );
}
